name    'puppet-zookeeper'
version '0.1.0'
source 'git://github.com/jbouse/puppet-zookeeper'
author 'jbouse'
license 'Apache License, Version 2.0'
summary 'Manage the Apache Zookeeper server or ensemble'
description 'Manage the Apache Zookeeper server or ensemble'
project_page 'https://github.com/jbouse/puppet-zookeeper'

dependency 'puppetlabs/java', '>= 1.0.1'
